### ISSUE TITLE
Paybox System - Axios vulnerability - Please update the published package on NPM 

### ISSUE THREAD

**Issue by RiusmaX** [adriantombu/packages#17]
Hi,

First of all, thanks for your great work!

The version of axios in your module Paybox System published on NPM has a high vunerability (corrected by dependabot on your repo).

Can you just publish this version on NPM please? Because I can't use your git repo as source in my package.json to fix the problem :/

In advance, thanks :)

**Comment by adriantombu** [comment]
Hey @RiusmaX good news I intended to look at this repo this week, so it will be fixed by the end of the week as soon as I have some free time to handle this 😊

**Comment by RiusmaX** [comment]
Ok thanks a lot :)

**Comment by adriantombu** [comment]
paybox-system has been updated and published with the latest axios version ! Lemme dig my brain for your other issue now ^^
