### ISSUE TITLE
Paybox System - Amount not working with decimals

### ISSUE THREAD

**Issue by RiusmaX** [adriantombu/packages#18]
Hi, 

I can't get the payment to work with decimals.

I'm using your lib in JavaScript with NextJS on the api side.

Everthing is working find but I can't use decimals.

This is my code :

```javascript
const payment = Paybox.create({
  payboxSandbox: true,
  payboxSite: process.env.PAYBOX_SITE,
  payboxRang: process.env.PAYBOX_RANG,
  payboxIdentifiant: process.env.PAYBOX_IDENTIFIANT,
  payboxHmac: process.env.PAYBOX_HMAC,
  payboxEffectue: process.env.PAYBOX_RETURN_URL,
  payboxRefuse: process.env.PAYBOX_RETURN_URL,
  payboxAnnule: process.env.PAYBOX_RETURN_URL,
  payboxAttente: process.env.PAYBOX_RETURN_URL,
  payboxRepondreA: process.env.PAYBOX_RETURN_URL,
  amount: 4990, // I've tried '4990' 49,90 49.90, etc... nothing change
  email: 'foo@bar.com',
  reference: transaction._id
})

const form = await payment.form()
```

This is the payment object from Paybox.create() method :

```javascript
{
  PBX_SITE: 'X',
  PBX_RANG: 'X',
  PBX_IDENTIFIANT: 'X',
  PBX_ARCHIVAGE: 'X',
  PBX_HMAC: 'X',
  PBX_TOTAL: '0000499000',
  PBX_DEVISE: '978',
  PBX_CMD: 606ed4db16ab275236b31100,
  PBX_PORTEUR:  'foo@bar.com',
  PBX_RETOUR: 'amount:M;paymentId:R;transactionId:T;authorizationId:A;cardType:P;cardNumber:N;cardExpiration:D;error:E;payboxRef:S;signature:K;',
  PBX_RUF1: 'POST',
  PBX_TIME: '04042021120307',
  PBX_HASH: 'SHA512',
  PBX_EFFECTUE: 'http://localhost:3333/result',
  PBX_REFUSE: 'http://localhost:3333/result',
  PBX_ANNULE: 'http://localhost:3333/result',
  PBX_ATTENTE: 'http://localhost:3333/result',
  PBX_REPONDRE_A: 'http://localhost:3333/result'
}
```

When i submit this form, I go to Paybox payment page but the amount is 4990.00€, not 49.90€ as expected. I've tried various ways to set it but with no success.

It's working when I set `amount: 35`, without multiplying by 100.

Maybe the problem comes from this function in your code :

```javascript

  private formatAmount(amount: number | string): string {
    return `${parseInt(amount.toString(), 10) * 100}`.padStart(10, '0')
  }
```
If you could point me in the right direction to make this work, I would be eternally grateful.

Thanks in advance.

**Comment by adriantombu** [comment]
I haven't used Paybox for quite some time, maybe there was some changes in the paybox API, I'll try to find an up to date documentation to check everything as soon as possible !

**Comment by RiusmaX** [comment]
Super, thank you very much, I imagine that it must not be easy, their system is not the easiest to implement...
If I can help in any way, don't hesitate :)

**Comment by adriantombu** [comment]
Ok so here's the doc I found regarding `PBX_TOTAL` https://www.paybox.com/espace-integrateur-documentation/dictionnaire-des-donnees/paybox-system/ 

```
PBX_TOTAL
Format System : 3 à 10 chiffres. Obligatoire.
Format Direct : 10 chiffres. Obligatoire.
Montant total de la transaction en centimes (sans virgule ni point).
Exemple pour 19€90 : 1990
```

I think that when I created this library, I simply didn't need the decimals and as a lazy developer I just mulitplied the price by 100, banishing all use of the decimals forever 🙈

I'm gonna fix that, and as it's quite a breaking change I'll bump the version too!

**Comment by adriantombu** [comment]
@RiusmaX `v2.0.0` is published on npm https://www.npmjs.com/package/@adriantombu/paybox-system

Thanks again for your report, I will never understand how and why that `* 100` ended up in the initial code 2 years ago and no one reported it 😳

**Comment by RiusmaX** [comment]
Thanks a lot for your reactivity, you are at the top :D
