### ISSUE TITLE
vat-number has a high severity vulnerability via a transitive dependency

### ISSUE THREAD

**Issue by mac-cain13** [adriantombu/packages#23]
Thanks a lot for your very useful packages!

The package `underscore` is vulnerable to Arbitrary Code Execution. The `@adriantombu/vat-number` package currently depends on a vulnerable version of `underscore` through it's dependency on the `soap` package. 

Would you be so kind to update the soap dependency to `0.39.0`? This would resolve this vulnerability.

**Comment by adriantombu** [comment]
Hey @mac-cain13 thanks for reaching out and the PR!

**Comment by adriantombu** [comment]
Package updated on npm with v2.0.14 : https://www.npmjs.com/package/@adriantombu/vat-number
