### ISSUE TITLE
vat-number has a moderate severity vulnerability via transitive dependency xmldom

### ISSUE THREAD

**Issue by mac-cain13** [adriantombu/packages#28]
Thanks a lot for your very useful packages once again!

The package xmldom is [vulnerable to misinterpretation of malicious XML input](https://github.com/advisories/GHSA-5fg8-2547-mr8q). The @adriantombu/vat-number package currently depends on a vulnerable version of xmldom through it's dependency on the soap package.

Would you be so kind to update the soap dependency to 0.42.0? This would resolve this vulnerability.

**Comment by adriantombu** [comment]
Hello @mac-cain13 thanks for raising this issue!
I was a bit busy during the summer but I just upgraded all the packages (not only vat-number) that needed upgrades ☺️

**Comment by mac-cain13** [comment]
Awesome! Thanks a lot for allocating some of your time to do maintenance work. Highly appreciated!
