### ISSUE TITLE
Provide UMD builds

### ISSUE THREAD

**Issue by drzraf** [adriantombu/packages#9]
I'm currently using the node version of `openstack-swift` (ES6-import-based) which works well.
But I'd like to use it in another context (Jasmine on Browser using Karma) for which an UMD build would be way more suitable.
Do you think it'd be possible?

**Comment by adriantombu** [comment]
This package depends heavily on https://github.com/pkgcloud/pkgcloud and it works for node.js only and not the front, so I can't do anything about it unfortunately 😔

**Comment by drzraf** [comment]
I just opened https://github.com/pkgcloud/pkgcloud/issues/694 to get more clarification about this.
